# The Basics

In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3,], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#Get dimensions
a.ndim

1

In [6]:
b.ndim

2

In [7]:
b.shape

(2, 3)

In [11]:
#Get the type
a.dtype

dtype('int16')

In [13]:
#Get size
a.itemsize

2

In [14]:
#Get the total size
a.size

3

In [15]:
a.nbytes

6

In [17]:
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


# Accesing/Changing specific elements, rows, columns, etc

In [23]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
a.shape

(2, 7)

In [25]:
#Get a specific element [r, c]
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [38]:
a[1,5]

np.int32(13)

In [39]:
#Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
#Get specific column
a[:, 2]

array([ 3, 10])

In [41]:
#Getting a little more fancy [starindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [42]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [43]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [46]:
#3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
#Get specific element (work outside in)
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [50]:
#Replace
b[:, 1, :] = [[9,9],[8,8]]

In [51]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [52]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [53]:
a[:, 2] = 20

In [54]:
a

array([[ 1,  2, 20,  4,  5],
       [ 6,  7, 20,  9, 10]])

# Initializing Different Types of Arrays

In [58]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
#All 1s matriz
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [61]:
#Any other number
np.full((2,2),99, dtype='int32')

array([[99, 99],
       [99, 99]])

In [62]:
#Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [63]:
#Random decimal numbers
np.random.rand(4,2)


array([[0.92212335, 0.11524268],
       [0.37164428, 0.22834463],
       [0.53344227, 0.44527603],
       [0.31951152, 0.68421069]])

In [64]:
np.random.random_sample(a.shape)

array([[0.63806826, 0.34205589, 0.14326839, 0.11874516, 0.80032063],
       [0.95289925, 0.75867312, 0.95465717, 0.37374536, 0.15369998]])

In [71]:
#Random Intenger values
np.random.randint(7)

6

In [81]:
np.random.randint(-4,7, size=(3,3))

array([[-3, -4,  5],
       [ 2,  0, -4],
       [-4, -4, -2]])

In [83]:
#The indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [92]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [96]:
a = np.array([1,2,3,])
b = a.copy()
b[0]= 100
print(a)

[1 2 3]


# Mathematics

In [97]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [98]:
a + 2

array([3, 4, 5, 6])

In [99]:
a - 2

array([-1,  0,  1,  2])

In [100]:
a * 2

array([2, 4, 6, 8])

In [101]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [102]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [103]:
a ** 2

array([ 1,  4,  9, 16])

In [104]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [105]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [106]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

### Linear Algebra

In [107]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [108]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [109]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

### Reference docs docs scipy org routines linalg

In [111]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.min(stats)

np.int32(1)

In [117]:
np.max(stats, axis =1)

array([3, 6])

In [114]:
np.sum(stats)

np.int32(21)

# Reorganizing Arrays

In [124]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [127]:
# Vertical stacking vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [128]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous
### Load Data from File

In [135]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3],
       [  3,  42,  12,  33, 766,  75,   4,  55],
       [  1,  22,  33,   1, 999,  11,   2,   1]])

#### Boolean Masking and Advanced Indexing

In [136]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False],
       [False, False, False, False,  True,  True, False,  True],
       [False, False, False, False,  True, False, False, False]])

In [137]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999])

In [138]:
#You can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [139]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True])

In [140]:
np.all(filedata > 50,axis = 0)

array([False, False, False, False,  True, False, False, False])

In [141]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False,  True],
       [False, False, False, False, False, False, False, False]])

In [ ]:
a[2:4,0:2]
a[[0,1,2,3],[1,2,3,4]]
a[0,4,5], 3:]